# Generated by Django 5.1.5 on 2025-05-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='query',
            new_name='search_query',
        ),
    ]
