# Generated by Django 5.1.5 on 2025-05-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='company_name',
        ),
    ]
