# Generated by Django 5.1.5 on 2025-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_rename_query_searchhistory_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
