# Generated by Django 5.1.5 on 2025-05-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_remove_contactus_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
