# Generated by Django 5.1.5 on 2025-05-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_contactus_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
