# Generated by Django 5.1.5 on 2025-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_contactus_company_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='price_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pricing',
            name='product_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
