# Generated by Django 5.1.5 on 2025-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_pricing_price_id_pricing_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
