# Generated by Django 5.1.5 on 2025-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_pricing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
