# Generated by Django 5.1.5 on 2025-05-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
