# Generated by Django 5.1.5 on 2025-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_subscriptionhistory_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
