# Generated by Django 5.1.5 on 2025-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(default='videos/default_video.mp4', upload_to='blog_videos/'),
        ),
    ]
