# Generated by Django 5.1.5 on 2025-01-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_blogpost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='payment_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='receipt',
            new_name='subscription_id',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='interval',
            field=models.CharField(default='month', max_length=50),
        ),
    ]
