# Generated by Django 5.1.5 on 2025-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_usersubscription_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
