# Generated by Django 5.1.5 on 2025-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_rename_payment_id_usersubscription_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
