# Generated by Django 5.1.5 on 2025-02-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_usersubscription_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255, null=True)),
                ('website_url', models.URLField(null=True)),
                ('product_link', models.URLField(null=True)),
                ('product_title', models.CharField(max_length=255, null=True)),
                ('product_images', models.TextField(null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_availability_status', models.CharField(max_length=100, null=True)),
                ('product_availability_quantity', models.IntegerField(null=True)),
                ('product_sold_quantity', models.IntegerField(null=True)),
                ('product_remaining_quantity', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('shipping', models.CharField(max_length=255, null=True)),
                ('est_arrival', models.DateField(null=True)),
                ('condition', models.CharField(max_length=255, null=True)),
                ('condition_id', models.CharField(max_length=100, null=True)),
                ('condition_descriptors', models.TextField(null=True)),
                ('condition_values', models.TextField(null=True)),
                ('condition_additional_info', models.TextField(null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('auction_id', models.CharField(max_length=100, null=True)),
                ('bid_count', models.IntegerField(null=True)),
                ('certified_seller', models.BooleanField(null=True)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('current_bid_currency', models.CharField(max_length=10, null=True)),
                ('favorited_count', models.IntegerField(null=True)),
                ('highest_bidder', models.CharField(max_length=255, null=True)),
                ('listing_id', models.CharField(max_length=100, null=True)),
                ('integer_id', models.IntegerField(null=True)),
                ('is_owner', models.BooleanField(null=True)),
                ('listing_type', models.CharField(max_length=100, null=True)),
                ('lot_string', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('starting_price_currency', models.CharField(max_length=10, null=True)),
                ('is_closed', models.BooleanField(null=True)),
                ('user_bid_status', models.CharField(max_length=100, null=True)),
                ('user_max_bid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('return_terms_returns_accepted', models.BooleanField(null=True)),
                ('return_terms_refund_method', models.CharField(max_length=100, null=True)),
                ('return_terms_return_shipping_cost_payer', models.CharField(max_length=100, null=True)),
                ('return_terms_return_period_value', models.IntegerField(null=True)),
                ('return_terms_return_period_unit', models.CharField(max_length=50, null=True)),
                ('payment_methods', models.TextField(null=True)),
            ],
        ),
    ]
