# Generated by Django 5.1.5 on 2025-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_alter_customuser_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='est_arrival',
            new_name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_shipping_cost_currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_shipping_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='buying_options',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='current_bid_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='current_bid_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_estimated_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_estimated_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_price_currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_price_to_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_used_for_estimate',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_carrier_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_service_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unique_bidder_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='certified_seller',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_bid_currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorited_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_owner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_availability_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_remaining_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sold_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_terms_return_period_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_terms_returns_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price_currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_max_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
