# Generated by Django 5.1.5 on 2025-03-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Favourites',
        ),
    ]
